Repository TeamPGM/PagerMaid_Plugins_Pyro, pull requests merged in 2022-06, with the labels that each got.

#2 diss 儒雅随和版祖安语录
  diss/main.py
  list.json
Labels: enhancement

#4 xtao-some 新增 wiki 功能
  list.json
  xtao-some/main.py
Labels: enhancement

#5 xtao-some 修复 wiki
  list.json
  xtao-some/main.py
Labels: bug

#6 pmcaptcha 验证失败标已读
  list.json
  pmcaptcha/main.py
Labels: enhancement

#11 pmcaptcha 中细微的英语语法改动
  list.json
  pmcaptcha/main.py
Labels: documentation

#19 修复了一些东西 并且让代码看起来更shit了
  dc/main.py
  list.json
  premium/main.py
Labels: enhancement
